using Normal.Realtime;
using Normal.Realtime.Serialization;

namespace UnityEngine.XR.Interaction.Toolkit.Examples
{
    [RealtimeModel]
    public partial class NormcoreProgressModel
    {
        [RealtimeProperty(1, true, true)] 
        private int _currentStep;
    }
}

/* ----- Begin Normal Autogenerated Code ----- */
namespace UnityEngine.XR.Interaction.Toolkit.Examples {
    public partial class NormcoreProgressModel : RealtimeModel {
        public int currentStep {
            get {
                return _currentStepProperty.value;
            }
            set {
                if (_currentStepProperty.value == value) return;
                _currentStepProperty.value = value;
                InvalidateReliableLength();
                FireCurrentStepDidChange(value);
            }
        }
        
        public delegate void PropertyChangedHandler<in T>(NormcoreProgressModel model, T value);
        public event PropertyChangedHandler<int> currentStepDidChange;
        
        public enum PropertyID : uint {
            CurrentStep = 1,
        }
        
        #region Properties
        
        private ReliableProperty<int> _currentStepProperty;
        
        #endregion
        
        public NormcoreProgressModel() : base(null) {
            _currentStepProperty = new ReliableProperty<int>(1, _currentStep);
        }
        
        protected override void OnParentReplaced(RealtimeModel previousParent, RealtimeModel currentParent) {
            _currentStepProperty.UnsubscribeCallback();
        }
        
        private void FireCurrentStepDidChange(int value) {
            try {
                currentStepDidChange?.Invoke(this, value);
            } catch (System.Exception exception) {
                UnityEngine.Debug.LogException(exception);
            }
        }
        
        protected override int WriteLength(StreamContext context) {
            var length = 0;
            length += _currentStepProperty.WriteLength(context);
            return length;
        }
        
        protected override void Write(WriteStream stream, StreamContext context) {
            var writes = false;
            writes |= _currentStepProperty.Write(stream, context);
            if (writes) InvalidateContextLength(context);
        }
        
        protected override void Read(ReadStream stream, StreamContext context) {
            var anyPropertiesChanged = false;
            while (stream.ReadNextPropertyID(out uint propertyID)) {
                var changed = false;
                switch (propertyID) {
                    case (uint) PropertyID.CurrentStep: {
                        changed = _currentStepProperty.Read(stream, context);
                        if (changed) FireCurrentStepDidChange(currentStep);
                        break;
                    }
                    default: {
                        stream.SkipProperty();
                        break;
                    }
                }
                anyPropertiesChanged |= changed;
            }
            if (anyPropertiesChanged) {
                UpdateBackingFields();
            }
        }
        
        private void UpdateBackingFields() {
            _currentStep = currentStep;
        }
        
    }
}
/* ----- End Normal Autogenerated Code ----- */
